version: 2
jobs:

  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "ON"
    steps:
      - checkout
      - run: go build -o gorpn main.go

  test:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "ON"
    steps:
      - checkout
      - run: go test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
